web:
  image: nginx:1.9.11
  container_name: rancher-web
  restart: always
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - /certs:/certs:ro
  links:
    - rancher
  ports:
    - "80:80"
    - "443:443"
  env_file: ./rancher.env

rancher:
  image: rancher/server:v0.59.1
  container_name: rancher
  restart: always
  volumes_from:
    - rancher-data
  volumes:
    - /certs/cert.pem:/ca.crt:ro
  links:
    - db
  env_file:
    - ./rancher.env
    - ./database.env

rancher-data:
  image: rancher/server:v0.59.1
  container_name: rancher-data
  entrypoint: /bin/echo
  command: "Data rancher"

db:
  image: mariadb:10.1.12
  container_name: rancher-db
  restart: always
  volumes_from:
    - db-data
  volumes:
    - ./rancher.cnf:/etc/mysql/conf.d/rancher.cnf:ro
    - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 1
  env_file: ./database.env

db-data:
  image: mariadb:10.1.12
  container_name: rancher-db-data
  entrypoint: /bin/echo
  command: "Data db"
